services:
  www:
    build:
      context: .
      target: prod
    ports:
      - "80:80"
    volumes:
      - ".env.prod:/var/www/html/.env.local:ro"
    links:
      - database
    extra_hosts:
      - host.docker.internal:host-gateway

  database:
    image: postgres:16.0
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
