version: "3.3"

services:
  www:
    build: docker/www/
    ports:
      - "80:80"
    volumes:
      - ".:/var/www/html:rw"
      - "./docker/www/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro"
    links:
      - database
    extra_hosts:
      - host.docker.internal:host-gateway

  database:
    image: mysql:8.1
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
