version: "3.3"

services:
  www:
    build:
      context: docker/www/
      dockerfile: Dockerfile
      target: dev
    ports:
      - "80:80"
    volumes:
      - ".:/var/www/html:rw"
      - "./docker/www/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro"
    links:
      - database
    extra_hosts:
      - host.docker.internal:host-gateway

  database:
    image: postgres:16.0
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
